// Spelling word bank for the Spellwright (Utah 3.R.3.b–e, plus grade-2 review).
// See docs/curriculum.md, "Spelling and word study".
//
// Each WORDS entry is { w, p, s, lvl } (compounds also have parts):
//   w   – the word with exactly ONE [bracketed] span: the tricky part that a ★
//         "missing letters" task blanks out (fr[ie]nd → fr _ _ nd). Removing the
//         brackets gives the correct American spelling. Use parseWord() to split it.
//   p   – a pattern id from PATTERNS.
//   s   – one sentence from the Sundered Isles that uses the exact word (≤ 14 words).
//   lvl – 1 shorter/common, 2 typical grade 3, 3 stretch.
//   parts – compounds only: the two words (["moon", "light"]).
//
// Bracket conventions are noted above each pattern's section below.

export const PATTERNS = {
  closed: {
    label: "Closed syllables",
    rule: "A closed syllable ends with a consonant, so its vowel makes its short sound: rab-bit, bas-ket.",
    standard: "3.R.3.b",
  },
  open: {
    label: "Open syllables",
    rule: "An open syllable ends with a vowel, so the vowel says its name: ro-bot, ti-ger.",
    standard: "3.R.3.b",
  },
  vce: {
    label: "Silent-e syllables",
    rule: "A silent e at the end makes the vowel before it say its name: cup-cake, ex-plode.",
    standard: "3.R.3.b",
  },
  vteam: {
    label: "Vowel teams",
    rule: "Two or more letters can team up to make one vowel sound: ai in raincoat, ee in seaweed, igh in highway.",
    standard: "3.R.3.b",
  },
  rcontrolled: {
    label: "Bossy R",
    rule: "An r after a vowel bosses its sound: ar in garden, or in fortress, and er, ir and ur all sound alike.",
    standard: "3.R.3.b",
  },
  cle: {
    label: "Consonant-le",
    rule: "At the end of a word, a consonant plus le makes its own syllable: bat-tle, can-dle.",
    standard: "3.R.3.b",
  },
  prefix: {
    label: "Prefixes",
    rule: "A prefix snaps onto the front of a word to change its meaning, and both parts keep every letter: mis + spell = misspell.",
    standard: "3.R.3.c",
  },
  suffix_ing_ed: {
    label: "Adding -ing and -ed",
    rule: "If a word ends in one short vowel and one consonant, double the consonant (hop, hopping), and if it ends in a silent e, drop the e (smile, smiled).",
    standard: "3.R.3.c",
  },
  suffix_es_ies: {
    label: "Plurals with -es and -ies",
    rule: "Add -es after s, x, z, ch or sh (boxes, wishes), and change a consonant + y to -ies (berries).",
    standard: "3.R.3.c",
  },
  suffix_er_est: {
    label: "Comparing with -er and -est",
    rule: "Add -er to compare two things and -est for the most, doubling (bigger), dropping the e (bravest) or changing y to i (happier) when needed.",
    standard: "3.R.3.c",
  },
  suffix_tion: {
    label: "The -tion ending",
    rule: "The 'shun' sound at the end of a word is usually spelled -tion: ac-tion, po-tion.",
    standard: "3.R.3.c",
  },
  suffix_ful_less: {
    label: "-ful, -less, -ly and -ness",
    rule: "These endings just snap on (careful, fearless, quickly, darkness), but a final y usually changes to i (happiness), and -ful has only one l.",
    standard: "3.R.3.c",
  },
  schwa: {
    label: "Hidden-sound words",
    rule: "In a quiet syllable, a vowel can mumble a lazy 'uh,' so you have to remember which letter it is: a-gain, lem-on.",
    standard: "3.R.3.d",
  },
  irregular: {
    label: "Wild words",
    rule: "Wild words don't play by the rules, so we learn their tricky parts by heart: friend, said, because.",
    standard: "3.R.3.e",
  },
  compound: {
    label: "Compound words",
    rule: "Two whole words join to make one new word, and each part keeps all its letters: ship + wreck = shipwreck.",
    standard: "2.R.3",
  },
  digraph_review: {
    label: "Consonant teams",
    rule: "ph can say f (dolphin), ch can say k (school), and right after a short vowel we use tch (catch) and dge (bridge).",
    standard: "2.R.3",
  },
  silent_review: {
    label: "Silent letters",
    rule: "Some letter pairs have a silent partner: kn in knight, wr in wrist, mb in thumb, gn in gnome.",
    standard: "2.R.3",
  },
  diphthong_review: {
    label: "Diphthongs and friends",
    rule: "oi, ou, au and oo make new vowel sounds, and at the end of a syllable we usually write oy, ow or aw instead: roy-al, tow-er, claw.",
    standard: "2.R.3",
  },
};

export const WORDS = [
  // closed: the consonants where the syllables split (rab|bit, pump|kin), the
  // -ck or -ic ending, or the short vowel in a mumbled second syllable (bask_et).
  { w: "ra[bb]it", p: "closed", s: "The rabbit fiend is cute, fluffy, and absolutely furious.", lvl: 1 },
  { w: "ki[tt]en", p: "closed", s: "The ship's kitten is the real captain, and everyone knows it.", lvl: 1 },
  { w: "bu[ck]et", p: "closed", s: "The droid bails water with a bucket that has a hole in it.", lvl: 1 },
  { w: "ti[ck]et", p: "closed", s: "An airship ticket costs ten gold, or one very good joke.", lvl: 1 },
  { w: "bask[e]t", p: "closed", s: "The monkey keeps a basket of stolen spoons under its bed.", lvl: 1 },
  { w: "inse[ct]", p: "closed", s: "A giant insect fiend buzzed past, wearing the Knight's lost boot.", lvl: 1 },
  { w: "magn[e]t", p: "closed", s: "A giant magnet pulled every sword, spoon, and helmet off the ship.", lvl: 2 },
  { w: "pu[mp]kin", p: "closed", s: "The fiend disguised itself as a pumpkin, but it kept blinking.", lvl: 2 },
  { w: "a[tt]ack", p: "closed", s: "The crab army refuses to attack until after its nap.", lvl: 2 },
  { w: "hun[dre]d", p: "closed", s: "Honest Hal swears this smelly boot is a hundred years old.", lvl: 2 },
  { w: "su[mm]it", p: "closed", s: "At the summit of the volcano, a fiend was selling lemonade.", lvl: 2 },
  { w: "ca[ct]us", p: "closed", s: "Never hug a cactus, even if it looks lonely.", lvl: 2 },
  { w: "tra[ff]ic", p: "closed", s: "Airship traffic over the harbor is so bad that seagulls walk instead.", lvl: 2 },
  { w: "sa[ndw]ich", p: "closed", s: "Honest Hal sold us a sandwich, and it was mostly sand.", lvl: 3 },
  { w: "ha[mm]ock", p: "closed", s: "The droid lost a fight with a hammock and won't talk about it.", lvl: 3 },
  { w: "fantast[ic]", p: "closed", s: "'Fantastic,' said the droid, in its least excited voice.", lvl: 3 },
  { w: "hi[cc]up", p: "closed", s: "One hiccup from the Leviathan knocked three boats into next week.", lvl: 3 },

  // open: the vowel that ends the open syllable. It says its name with ONE letter
  // (ti-ger, not tie-ger or ty-ger).
  { w: "r[o]bot", p: "open", s: "Never call the droid a robot unless you enjoy long, chilly silences.", lvl: 1 },
  { w: "m[u]sic", p: "open", s: "Sea sirens sing music so lovely that pirates forget to steer.", lvl: 1 },
  { w: "t[i]ger", p: "open", s: "The tiger fiend guards the temple, but it naps every afternoon.", lvl: 1 },
  { w: "p[i]lot", p: "open", s: "Our airship pilot is a parrot, and honestly, it's not that bad.", lvl: 1 },
  { w: "z[e]ro", p: "open", s: "The fiend has zero hit points left and is very upset about it.", lvl: 1 },
  { w: "t[i]ny", p: "open", s: "The droid insists its tiny pirate hat is terrifying.", lvl: 1 },
  { w: "fr[o]zen", p: "open", s: "On the ice island, even the waterfall is frozen mid-splash.", lvl: 1 },
  { w: "s[e]cret", p: "open", s: "The secret door only opens if you tell it a joke.", lvl: 1 },
  { w: "s[i]lent", p: "open", s: "When the droid goes silent, it means the plan is terrible.", lvl: 2 },
  { w: "b[o]nus", p: "open", s: "Honest Hal throws in a free bonus: a slightly used sock.", lvl: 2 },
  { w: "cr[a]ter", p: "open", s: "The volcano's crater smells like rotten eggs and burnt toast.", lvl: 2 },
  { w: "[e]go", p: "open", s: "Captain Jumble's ego is bigger than his ship and twice as loud.", lvl: 2 },
  { w: "[e]qual", p: "open", s: "Split the gold into equal piles, or the parrot gets loud.", lvl: 2 },
  { w: "st[u]dent", p: "open", s: "The droid's only student keeps falling asleep, which the droid takes personally.", lvl: 2 },
  { w: "volc[a]no", p: "open", s: "Captain Jumble built his lair inside a volcano, because of course he did.", lvl: 2 },
  { w: "cl[i]mate", p: "open", s: "The fire island has a hot climate and very sweaty fiends.", lvl: 3 },
  { w: "mus[e]um", p: "open", s: "The ruins are basically a museum full of grumpy statues.", lvl: 3 },

  // vce: the vowel-consonant-e chunk (cupc[ake], not cupcaik).
  { w: "cupc[ake]", p: "vce", s: "Never trust a cupcake that hisses at you.", lvl: 1 },
  { w: "ins[ide]", p: "vce", s: "Something inside the treasure chest is snoring.", lvl: 1 },
  { w: "sunr[ise]", p: "vce", s: "The fiends attack at sunrise because they are rude morning people.", lvl: 1 },
  { w: "mist[ake]", p: "vce", s: "The droid has never made a mistake, according to the droid.", lvl: 1 },
  { w: "expl[ode]", p: "vce", s: "If the crystal starts humming, it is about to explode.", lvl: 2 },
  { w: "stamp[ede]", p: "vce", s: "A very slow stampede of turtles crossed the beach all afternoon.", lvl: 2 },
  { w: "rept[ile]", p: "vce", s: "The reptile fiend sheds its skin and leaves it everywhere.", lvl: 2 },
  { w: "esc[ape]", p: "vce", s: "The monkey planned an escape using one banana and a lot of confidence.", lvl: 2 },
  { w: "cost[ume]", p: "vce", s: "The fiend's ghost costume is just an old sheet with two holes.", lvl: 2 },
  { w: "tromb[one]", p: "vce", s: "A fiend playing the trombone is still a fiend, just louder.", lvl: 2 },
  { w: "div[ide]", p: "vce", s: "Divide the potions evenly, or the Knight drinks them all.", lvl: 2 },
  { w: "coll[ide]", p: "vce", s: "When two airships collide, both captains blame the seagulls.", lvl: 2 },
  { w: "exc[use]", p: "vce", s: "Captain Jumble always has an excuse, and it's always the wind.", lvl: 2 },
  { w: "surv[ive]", p: "vce", s: "Only a fuzzy Titan could survive the ice island's freezing wind.", lvl: 3 },
  { w: "crocod[ile]", p: "vce", s: "The crocodile fiend smiles a lot, which is never a good sign.", lvl: 3 },
  { w: "centip[ede]", p: "vce", s: "The centipede fiend needs a hundred tiny boots and complains about it.", lvl: 3 },
  { w: "telesc[ope]", p: "vce", s: "The sky-pirate's telescope is really two cups taped together.", lvl: 3 },

  // vteam: the team itself (ai, ay, ee, ea, oa, ow, ie, igh).
  { w: "r[ai]ncoat", p: "vteam", s: "The droid wears a raincoat to the beach, just in case.", lvl: 1 },
  { w: "cr[ay]on", p: "vteam", s: "The monkey drew a mustache on the treasure map with a crayon.", lvl: 1 },
  { w: "seaw[ee]d", p: "vteam", s: "The slime fiend is mostly seaweed and bad decisions.", lvl: 1 },
  { w: "p[ea]nut", p: "vteam", s: "The monkey will trade any secret for one peanut.", lvl: 1 },
  { w: "sailb[oa]t", p: "vteam", s: "Our first sailboat leaks, but only on the bottom.", lvl: 1 },
  { w: "shad[ow]", p: "vteam", s: "Every shadow in the ruins giggles when you turn around.", lvl: 1 },
  { w: "h[igh]way", p: "vteam", s: "Sky-pirates race down the cloud highway at sunset.", lvl: 1 },
  { w: "midn[igh]t", p: "vteam", s: "At midnight, the statues in the ruins quietly trade places.", lvl: 1 },
  { w: "expl[ai]n", p: "vteam", s: "Captain Jumble can't explain his own map, but he points at it proudly.", lvl: 2 },
  { w: "merm[ai]d", p: "vteam", s: "The mermaid gives great directions, as long as you're a fish.", lvl: 2 },
  { w: "stingr[ay]", p: "vteam", s: "A stingray slid under the boat like a flying rug.", lvl: 2 },
  { w: "betw[ee]n", p: "vteam", s: "The map says the gold is between a rock and a hard place.", lvl: 2 },
  { w: "ben[ea]th", p: "vteam", s: "Something huge is swimming beneath the ship, and it sounds hungry.", lvl: 2 },
  { w: "t[oa]ster", p: "vteam", s: "The droid is NOT a toaster, and it would like that noted.", lvl: 2 },
  { w: "bl[ow]fish", p: "vteam", s: "The blowfish puffed up until it looked like a spiky beach ball.", lvl: 2 },
  { w: "magp[ie]", p: "vteam", s: "A magpie stole the shiniest crystal and left a bottle cap.", lvl: 2 },
  { w: "ach[ie]ve", p: "vteam", s: "Achieve three stars and the droid will almost smile.", lvl: 3 },
  { w: "l[igh]tning", p: "vteam", s: "Lightning hit the mast, and now the parrot's feathers stick straight up.", lvl: 3 },

  // rcontrolled: the vowel + r. For er/ir/ur words that is the part kids mix up.
  { w: "thund[er]", p: "rcontrolled", s: "Titans love thunder, mostly because it sounds like clapping.", lvl: 1 },
  { w: "g[ar]den", p: "rcontrolled", s: "The temple has a secret garden full of very rude flowers.", lvl: 1 },
  { w: "t[ur]tle", p: "rcontrolled", s: "The island we camped on turned out to be a giant turtle.", lvl: 1 },
  { w: "corn[er]", p: "rcontrolled", s: "Something with too many eyes is watching us from the corner.", lvl: 1 },
  { w: "p[ur]ple", p: "rcontrolled", s: "The slime turned purple, which in slime language means 'oops.'", lvl: 1 },
  { w: "p[er]fect", p: "rcontrolled", s: "Captain Jumble rates his own singing a perfect ten out of ten.", lvl: 2 },
  { w: "pill[ar]", p: "rcontrolled", s: "One cracked pillar holds up the whole temple, so please tiptoe.", lvl: 2 },
  { w: "th[ir]sty", p: "rcontrolled", s: "The thirsty Titan drank half the lagoon, and the fish were not happy.", lvl: 2 },
  { w: "wh[ir]lpool", p: "rcontrolled", s: "Steer around the whirlpool unless you enjoy being very, very dizzy.", lvl: 2 },
  { w: "ret[ur]n", p: "rcontrolled", s: "Captain Jumble swore he would return, then got lost on the way.", lvl: 2 },
  { w: "f[or]tress", p: "rcontrolled", s: "The Iron Dominion's fortress has a moat full of grumpy eels.", lvl: 2 },
  { w: "arm[or]", p: "rcontrolled", s: "The Knight's armor squeaks, so sneaking is not an option.", lvl: 2 },
  { w: "sail[or]", p: "rcontrolled", s: "Every sailor knows never to whistle at the Leviathan.", lvl: 2 },
  { w: "harb[or]", p: "rcontrolled", s: "The harbor is so busy that even the fish wait in line.", lvl: 2 },
  { w: "squ[ir]rel", p: "rcontrolled", s: "A flying squirrel stole the map and sailed away, giggling.", lvl: 3 },
  { w: "s[ur]prise", p: "rcontrolled", s: "The treasure chest held a surprise: a smaller treasure chest.", lvl: 3 },
  { w: "h[urr]icane", p: "rcontrolled", s: "The hurricane blew the pirates' laundry all the way to the next island.", lvl: 3 },

  // cle: the consonant-le syllable (bat[tle], not battel).
  { w: "bat[tle]", p: "cle", s: "The battle ended when both fiends got distracted by a butterfly.", lvl: 1 },
  { w: "puz[zle]", p: "cle", s: "The temple door is a puzzle, and the answer is always 'push.'", lvl: 1 },
  { w: "can[dle]", p: "cle", s: "The fire fiend is just a grumpy candle with legs.", lvl: 1 },
  { w: "jun[gle]", p: "cle", s: "The jungle is so loud that even the plants seem to argue.", lvl: 1 },
  { w: "tem[ple]", p: "cle", s: "The old temple is guarded by a stone frog that tells terrible jokes.", lvl: 1 },
  { w: "bee[tle]", p: "cle", s: "The armored beetle shrugs off arrows but fears the Knight.", lvl: 1 },
  { w: "bot[tle]", p: "cle", s: "The message in the bottle just says, 'Bring snacks.'", lvl: 1 },
  { w: "pad[dle]", p: "cle", s: "We lost the paddle, so now the droid rows with its hat.", lvl: 1 },
  { w: "cas[tle]", p: "cle", s: "Captain Jumble's castle has a moat full of rubber ducks.", lvl: 2 },
  { w: "spar[kle]", p: "cle", s: "Lore Crystals sparkle brighter whenever someone nearby spells a word right.", lvl: 2 },
  { w: "scram[ble]", p: "cle", s: "Captain Jumble loves to scramble the letters on every sign.", lvl: 2 },
  { w: "rip[ple]", p: "cle", s: "A tiny ripple in the lagoon became a very large sea serpent.", lvl: 2 },
  { w: "whis[tle]", p: "cle", s: "The droid can whistle, but only one very sad note.", lvl: 2 },
  { w: "jug[gle]", p: "cle", s: "The monkey can juggle three coconuts and one very surprised fish.", lvl: 2 },
  { w: "tenta[cle]", p: "cle", s: "A single tentacle rose from the sea and waved politely.", lvl: 3 },
  { w: "barna[cle]", p: "cle", s: "One barnacle on our ship has been there longer than the captain.", lvl: 3 },
  { w: "ici[cle]", p: "cle", s: "An icicle dripped on the fire fiend, and it hissed like a kettle.", lvl: 3 },

  // prefix: the prefix itself (the affix rune). im- comes before b, m or p.
  { w: "[re]build", p: "prefix", s: "The crew had to rebuild the dock after a Titan sat on it.", lvl: 1 },
  { w: "[re]load", p: "prefix", s: "The Gunner must reload after every volley and grumbles every time.", lvl: 1 },
  { w: "[un]lock", p: "prefix", s: "Only a correctly spelled word can unlock the ancient door.", lvl: 1 },
  { w: "[un]lucky", p: "prefix", s: "The unlucky pirate found a treasure chest full of socks.", lvl: 1 },
  { w: "[pre]view", p: "prefix", s: "The droid gave us a preview of the plan: step one, panic.", lvl: 1 },
  { w: "[re]charge", p: "prefix", s: "Lore Crystals recharge in sunlight, just like lazy cats.", lvl: 2 },
  { w: "[un]known", p: "prefix", s: "An unknown fiend is hiding under the dock, and it smells like cheese.", lvl: 2 },
  { w: "[dis]appear", p: "prefix", s: "The ghost ship can disappear, but its terrible singing cannot.", lvl: 2 },
  { w: "[dis]honest", p: "prefix", s: "Honest Hal swears he has never been dishonest, except on weekdays.", lvl: 2 },
  { w: "[pre]heat", p: "prefix", s: "Preheat the volcano before baking your lava cookies.", lvl: 2 },
  { w: "[mis]spell", p: "prefix", s: "If you misspell a spell, it might turn into a sneeze.", lvl: 2 },
  { w: "[mis]fire", p: "prefix", s: "The cannon might misfire, so the droid stands way over there.", lvl: 2 },
  { w: "[in]visible", p: "prefix", s: "The invisible fiend keeps bumping into things and saying sorry.", lvl: 2 },
  { w: "[in]correct", p: "prefix", s: "Honest Hal's math is always incorrect, and always in his favor.", lvl: 2 },
  { w: "[dis]obey", p: "prefix", s: "The parrot will disobey every order except 'Want a cracker?'", lvl: 3 },
  { w: "[pre]historic", p: "prefix", s: "A prehistoric Titan woke up and asked what year it was.", lvl: 3 },
  { w: "[mis]behave", p: "prefix", s: "If the monkey starts to misbehave, hide your hats.", lvl: 3 },
  { w: "[im]possible", p: "prefix", s: "The droid says the odds are impossible, then helps anyway.", lvl: 3 },

  // suffix_ing_ed: the base word stays visible. Doubling: the added consonant
  // plus the next letter (hop[pi]ng). Drop-e: the ending after the e-less stem
  // (smil[ed], rid[ing]).
  { w: "hop[pi]ng", p: "suffix_ing_ed", s: "The monkey was hopping mad because someone ate its banana.", lvl: 1 },
  { w: "run[ni]ng", p: "suffix_ing_ed", s: "The slime tried running away, but slimes are extremely slow.", lvl: 1 },
  { w: "swim[mi]ng", p: "suffix_ing_ed", s: "The droid does not do swimming; it does sinking.", lvl: 1 },
  { w: "stop[pe]d", p: "suffix_ing_ed", s: "The airship stopped so fast that the parrot kept going.", lvl: 1 },
  { w: "grab[be]d", p: "suffix_ing_ed", s: "The monkey grabbed the map and ran up a palm tree.", lvl: 1 },
  { w: "smil[ed]", p: "suffix_ing_ed", s: "The sphinx smiled, which meant the pirate's answer was wrong.", lvl: 1 },
  { w: "rid[ing]", p: "suffix_ing_ed", s: "Riding a Titan feels like sitting on a mountain with hiccups.", lvl: 1 },
  { w: "shak[ing]", p: "suffix_ing_ed", s: "The whole temple started shaking when the Titan yawned.", lvl: 1 },
  { w: "trap[pe]d", p: "suffix_ing_ed", s: "A slime got trapped in a bucket and seemed pretty happy about it.", lvl: 2 },
  { w: "spot[te]d", p: "suffix_ing_ed", s: "The lookout spotted land, then admitted it was a whale.", lvl: 2 },
  { w: "chas[ed]", p: "suffix_ing_ed", s: "A flock of seagulls chased the droid all the way to the dock.", lvl: 2 },
  { w: "glid[ed]", p: "suffix_ing_ed", s: "The airship glided over the reef like a sleepy whale.", lvl: 2 },
  { w: "rescu[ed]", p: "suffix_ing_ed", s: "The Knight rescued a cat from a tree, and then the tree attacked.", lvl: 2 },
  { w: "danc[ing]", p: "suffix_ing_ed", s: "Skeleton pirates love dancing because their bones make great music.", lvl: 2 },
  { w: "begin[ni]ng", p: "suffix_ing_ed", s: "At the beginning of every quest, the droid says, 'This seems unwise.'", lvl: 3 },
  { w: "control[le]d", p: "suffix_ing_ed", s: "The giant fiend is secretly controlled by a tiny crab pulling levers.", lvl: 3 },
  { w: "explor[ing]", p: "suffix_ing_ed", s: "Exploring the ruins is fun until something follows you home.", lvl: 3 },

  // suffix_es_ies: the ending (box[es], berr[ies]).
  { w: "box[es]", p: "suffix_es_ies", s: "Honest Hal's boxes say 'treasure,' but they rattle like rocks.", lvl: 1 },
  { w: "wish[es]", p: "suffix_es_ies", s: "The wishing well grants three wishes, but only about soup.", lvl: 1 },
  { w: "beach[es]", p: "suffix_es_ies", s: "Some beaches on the crystal islands sparkle so much you need sunglasses.", lvl: 1 },
  { w: "berr[ies]", p: "suffix_es_ies", s: "These jungle berries make you burp bubbles for an hour.", lvl: 1 },
  { w: "sk[ies]", p: "suffix_es_ies", s: "Sky-pirates rule the skies, or at least the cloudy parts.", lvl: 1 },
  { w: "sp[ies]", p: "suffix_es_ies", s: "The Iron Dominion's spies wear fake mustaches, even the drones.", lvl: 1 },
  { w: "torch[es]", p: "suffix_es_ies", s: "Light the torches, or the temple statues start telling ghost stories.", lvl: 2 },
  { w: "tax[es]", p: "suffix_es_ies", s: "The tax fiend demands taxes on everything, even naps.", lvl: 2 },
  { w: "glitch[es]", p: "suffix_es_ies", s: "The droid calls its glitches 'bonus features.'", lvl: 2 },
  { w: "branch[es]", p: "suffix_es_ies", s: "Monkeys swing through the branches, dropping banana peels on fiends.", lvl: 2 },
  { w: "stor[ies]", p: "suffix_es_ies", s: "Old sailors tell stories about the Leviathan that get bigger every year.", lvl: 2 },
  { w: "arm[ies]", p: "suffix_es_ies", s: "Two fiend armies met, argued about snacks, and went home.", lvl: 2 },
  { w: "rub[ies]", p: "suffix_es_ies", s: "The cave glitters with rubies, or possibly red jellybeans.", lvl: 2 },
  { w: "compass[es]", p: "suffix_es_ies", s: "Captain Jumble owns six compasses, and they all point at him.", lvl: 3 },
  { w: "enem[ies]", p: "suffix_es_ies", s: "Captain Jumble keeps a list of enemies, and you are on page one.", lvl: 3 },
  { w: "batter[ies]", p: "suffix_es_ies", s: "The droid's batteries are low, and so is its patience.", lvl: 3 },

  // suffix_er_est: like -ing/-ed. Doubling: big[ge]r. y to i: happ[ie]r.
  // Drop-e or no change: the ending (brav[est], fast[est]).
  { w: "big[ge]r", p: "suffix_er_est", s: "Captain Jumble's hat gets bigger every time he loses.", lvl: 1 },
  { w: "fast[est]", p: "suffix_er_est", s: "The fastest airship in the harbor is powered by very angry bees.", lvl: 1 },
  { w: "happ[ie]r", p: "suffix_er_est", s: "The slime is happier now that it has a name: Herbert.", lvl: 1 },
  { w: "hot[te]st", p: "suffix_er_est", s: "The hottest pepper on the island made a fire fiend cry.", lvl: 1 },
  { w: "wet[te]r", p: "suffix_er_est", s: "The droid came out of the lagoon wetter than a fish.", lvl: 1 },
  { w: "funn[ie]st", p: "suffix_er_est", s: "The droid told its funniest joke, and nobody laughed, including the droid.", lvl: 1 },
  { w: "brav[est]", p: "suffix_er_est", s: "The bravest pirate on the ship is scared of one tiny crab.", lvl: 2 },
  { w: "dim[me]r", p: "suffix_er_est", s: "When a crystal grows dimmer, the fiends grow bolder.", lvl: 2 },
  { w: "thin[ne]st", p: "suffix_er_est", s: "The thinnest rope bridge on the island is also the bounciest.", lvl: 2 },
  { w: "angr[ie]st", p: "suffix_er_est", s: "The angriest fiend on the island is a crab named Doug.", lvl: 2 },
  { w: "tin[ie]st", p: "suffix_er_est", s: "The tiniest fiend in the Bestiary is a flea with a sword.", lvl: 2 },
  { w: "larg[est]", p: "suffix_er_est", s: "The largest wave of the year carried our ship onto a roof.", lvl: 2 },
  { w: "wis[est]", p: "suffix_er_est", s: "The wisest owl on the island only ever says, 'Who knows?'", lvl: 2 },
  { w: "heav[ie]st", p: "suffix_er_est", s: "The heaviest treasure chest is full of rocks, thanks to Honest Hal.", lvl: 3 },
  { w: "might[ie]st", p: "suffix_er_est", s: "The mightiest Titan is afraid of exactly one thing: mice.", lvl: 3 },
  { w: "sneak[ie]st", p: "suffix_er_est", s: "The sneakiest monkey stole the droid's hat while the droid was wearing it.", lvl: 3 },

  // suffix_tion: always [tion].
  { w: "ac[tion]", p: "suffix_tion", s: "Pick an action: attack, defend, or pretend to be a rock.", lvl: 1 },
  { w: "mo[tion]", p: "suffix_tion", s: "The rocking motion of the airship makes the parrot feel airsick.", lvl: 1 },
  { w: "po[tion]", p: "suffix_tion", s: "This potion tastes like old socks, but it heals you.", lvl: 1 },
  { w: "sta[tion]", p: "suffix_tion", s: "The droid's charging station is a bucket of warm sand.", lvl: 1 },
  { w: "cau[tion]", p: "suffix_tion", s: "Caution: the floor is lava, and this time we mean it.", lvl: 2 },
  { w: "frac[tion]", p: "suffix_tion", s: "The parrot always gets the smallest fraction of the gold.", lvl: 2 },
  { w: "inven[tion]", p: "suffix_tion", s: "The droid's newest invention is a hat for its hat.", lvl: 2 },
  { w: "direc[tion]", p: "suffix_tion", s: "The wind changed direction, and so did the very confused seagulls.", lvl: 2 },
  { w: "collec[tion]", p: "suffix_tion", s: "Captain Jumble keeps a collection of stolen vowels in a jar.", lvl: 2 },
  { w: "protec[tion]", p: "suffix_tion", s: "The Knight's shield gives protection from fire, ice, and bad poetry.", lvl: 2 },
  { w: "loca[tion]", p: "suffix_tion", s: "The map shows the secret location of a very ordinary sandwich.", lvl: 2 },
  { w: "addi[tion]", p: "suffix_tion", s: "Healing spells use addition to put your health points back.", lvl: 2 },
  { w: "atten[tion]", p: "suffix_tion", s: "Pay attention to the fiend behind you, said the droid, too late.", lvl: 2 },
  { w: "subtrac[tion]", p: "suffix_tion", s: "Every Knight strike is subtraction, and the fiend's health bar drops.", lvl: 3 },
  { w: "expedi[tion]", p: "suffix_tion", s: "Our expedition to the ice island needs mittens, maps, and courage.", lvl: 3 },
  { w: "celebra[tion]", p: "suffix_tion", s: "After the battle, the celebration lasted until the parrot fell asleep.", lvl: 3 },

  // suffix_ful_less: the ending, or the i that replaced a y (happ[i]ness).
  { w: "care[ful]", p: "suffix_ful_less", s: "Be careful with that cannon; it goes off when it's nervous.", lvl: 1 },
  { w: "fear[less]", p: "suffix_ful_less", s: "The fearless Knight only screamed a little when the spider waved.", lvl: 1 },
  { w: "harm[less]", p: "suffix_ful_less", s: "This fiend looks scary but is harmless, unless you are a sandwich.", lvl: 1 },
  { w: "quick[ly]", p: "suffix_ful_less", s: "The slime quickly split into two slimes, then four, then lots.", lvl: 1 },
  { w: "dark[ness]", p: "suffix_ful_less", s: "Something in the darkness sneezed, and it sounded huge.", lvl: 1 },
  { w: "weak[ness]", p: "suffix_ful_less", s: "Every fiend has a weakness, and this one hates bad puns.", lvl: 1 },
  { w: "kind[ness]", p: "suffix_ful_less", s: "A little kindness turned the angry sea serpent into a pen pal.", lvl: 1 },
  { w: "power[ful]", p: "suffix_ful_less", s: "The most powerful Titan is also the most ticklish.", lvl: 2 },
  { w: "boast[ful]", p: "suffix_ful_less", s: "Boastful Captain Jumble named three islands after his own mustache.", lvl: 2 },
  { w: "use[less]", p: "suffix_ful_less", s: "Honest Hal's map is useless, but it is very nicely folded.", lvl: 2 },
  { w: "price[less]", p: "suffix_ful_less", s: "The priceless crystal turned out to be a glass doorknob.", lvl: 2 },
  { w: "safe[ly]", p: "suffix_ful_less", s: "The airship landed safely, if you don't count the tree.", lvl: 2 },
  { w: "eas[i]ly", p: "suffix_ful_less", s: "The monkey easily outsmarted the Iron Dominion's best spy.", lvl: 2 },
  { w: "happ[i]ness", p: "suffix_ful_less", s: "The droid measures happiness in fully charged batteries.", lvl: 2 },
  { w: "plent[i]ful", p: "suffix_ful_less", s: "Gold is plentiful on this island, but so are mosquitoes.", lvl: 3 },
  { w: "final[ly]", p: "suffix_ful_less", s: "The fiend finally fell asleep after the droid read it the rules.", lvl: 3 },
  { w: "sudden[ly]", p: "suffix_ful_less", s: "Suddenly, the floor stood up and walked away.", lvl: 3 },

  // schwa: the vowel that mumbles "uh".
  { w: "[a]gain", p: "schwa", s: "Captain Jumble lost again and blamed the weather.", lvl: 1 },
  { w: "[a]round", p: "schwa", s: "The airship flew around the volcano twice, just to look cool.", lvl: 1 },
  { w: "lem[o]n", p: "schwa", s: "One sip of lemon juice turned the slime inside out.", lvl: 1 },
  { w: "an[i]mal", p: "schwa", s: "Every animal on the ship has a job, except the goat.", lvl: 1 },
  { w: "pir[a]te", p: "schwa", s: "The pirate demanded our gold, then asked us for directions home.", lvl: 1 },
  { w: "parr[o]t", p: "schwa", s: "The parrot repeats everything you say, especially the embarrassing parts.", lvl: 1 },
  { w: "lev[e]l", p: "schwa", s: "Level up enough, and the droid might call you 'pretty okay.'", lvl: 1 },
  { w: "sign[a]l", p: "schwa", s: "The lighthouse signal means 'danger,' or possibly 'dinner.'", lvl: 2 },
  { w: "b[a]lloon", p: "schwa", s: "The droid rode a balloon over the island, complaining the whole way.", lvl: 2 },
  { w: "trav[e]l", p: "schwa", s: "Titans travel by stomping, which is very hard on beaches.", lvl: 2 },
  { w: "cann[o]n", p: "schwa", s: "Our cannon fires coconuts, which works surprisingly well.", lvl: 2 },
  { w: "cany[o]n", p: "schwa", s: "The crystal canyon echoes every word, so whisper your secrets.", lvl: 2 },
  { w: "cryst[a]l", p: "schwa", s: "Captain Jumble tried to steal a crystal and got zapped.", lvl: 2 },
  { w: "barr[e]l", p: "schwa", s: "The crew hid inside a barrel that was already full of pickles.", lvl: 2 },
  { w: "summ[o]n", p: "schwa", s: "To summon a Titan, you must write its grand entrance.", lvl: 2 },
  { w: "ev[e]ry", p: "schwa", s: "Every fiend on this island is allergic to good spelling.", lvl: 2 },
  { w: "vict[o]ry", p: "schwa", s: "Victory tastes like cake, says the droid, who cannot taste.", lvl: 3 },
  { w: "skel[e]ton", p: "schwa", s: "Captain Jumble's whole crew is one very busy skeleton.", lvl: 3 },

  // irregular: the letters that break the rules.
  { w: "bec[au]se", p: "irregular", s: "The droid wears a pirate hat because, it says, it looks intimidating.", lvl: 1 },
  { w: "fr[ie]nd", p: "irregular", s: "Every hero needs a friend who will carry the extra potions.", lvl: 1 },
  { w: "s[ai]d", p: "irregular", s: "'Arr,' said the parrot, which is the only word it knows.", lvl: 1 },
  { w: "p[eo]ple", p: "irregular", s: "The people of Driftwood Isle pay for everything with jokes.", lvl: 1 },
  { w: "c[oul]d", p: "irregular", s: "Nobody could explain why the volcano smelled like pancakes.", lvl: 1 },
  { w: "b[u]sy", p: "irregular", s: "The droid is too busy polishing its hat to fight.", lvl: 1 },
  { w: "b[ui]ld", p: "irregular", s: "The crew must build a raft before the volcano wakes up.", lvl: 1 },
  { w: "[is]land", p: "irregular", s: "This island is shaped like a boot and smells like one too.", lvl: 1 },
  { w: "[o]nce", p: "irregular", s: "Once a year, the fiends hold a talent show, and it's terrible.", lvl: 1 },
  { w: "[s]ure", p: "irregular", s: "Are you sure that's a treasure map and not a menu?", lvl: 1 },
  { w: "g[u]ess", p: "irregular", s: "Guess which cup the monkey hid the crystal under.", lvl: 1 },
  { w: "g[h]ost", p: "irregular", s: "The ghost pirate looks scary until he trips over his own cape.", lvl: 1 },
  { w: "m[o]nkey", p: "irregular", s: "A three-eyed monkey hides in every scene, and nobody knows why.", lvl: 1 },
  { w: "en[ough]", p: "irregular", s: "One spell was not enough, so the Spellwright cast seven.", lvl: 2 },
  { w: "thr[ough]", p: "irregular", s: "The airship sailed through a cloud shaped like Captain Jumble's nose.", lvl: 2 },
  { w: "th[ough]t", p: "irregular", s: "The Knight thought the cave was empty, but the cave disagreed.", lvl: 2 },
  { w: "ans[w]er", p: "irregular", s: "The sphinx wants an answer, and 'um' does not count.", lvl: 2 },
  { w: "min[ute]", p: "irregular", s: "'Wait one minute,' said the droid, which meant three hours.", lvl: 2 },
  { w: "o[cea]n", p: "irregular", s: "The ocean is so big that even the Leviathan gets lost.", lvl: 2 },
  { w: "spe[ci]al", p: "irregular", s: "Today's special at the pirate diner is fish, fish, or fish.", lvl: 2 },
  { w: "bel[ie]ve", p: "irregular", s: "Nobody will believe you tamed a Titan with a lullaby.", lvl: 2 },
  { w: "fav[o]rite", p: "irregular", s: "The droid's favorite sound is silence, followed by more silence.", lvl: 2 },
  { w: "capt[ai]n", p: "irregular", s: "Every captain needs a parrot, a hat, and a dramatic speech.", lvl: 2 },
  { w: "s[w]ord", p: "irregular", s: "The Knight's sword glows whenever a fiend tells a lie.", lvl: 2 },
  { w: "b[eau]tiful", p: "irregular", s: "The crystal cave is beautiful, as long as you hold your nose.", lvl: 3 },
  { w: "diff[e]rent", p: "irregular", s: "Every Titan is different, but they all hate bath time.", lvl: 3 },
  { w: "tr[ea]sure", p: "irregular", s: "X marks the treasure, but the monkey keeps moving the X.", lvl: 3 },

  // compound: the part kids most often get wrong, which is often the seam where
  // the two words meet (glo[ww]orm, pin[ea]pple).
  { w: "moonl[igh]t", p: "compound", parts: ["moon", "light"], s: "The fiends only come out by moonlight, because they're night owls.", lvl: 1 },
  { w: "sunfl[ow]er", p: "compound", parts: ["sun", "flower"], s: "The giant sunflower turns to watch you, which is a little rude.", lvl: 1 },
  { w: "campf[ire]", p: "compound", parts: ["camp", "fire"], s: "Around the campfire, the droid tells stories with no endings.", lvl: 1 },
  { w: "[air]ship", p: "compound", parts: ["air", "ship"], s: "Our airship runs on crystal power and the captain's loud singing.", lvl: 1 },
  { w: "ship[wr]eck", p: "compound", parts: ["ship", "wreck"], s: "The shipwreck is full of treasure and one octopus who wants it all.", lvl: 2 },
  { w: "ca[nn]onball", p: "compound", parts: ["cannon", "ball"], s: "The cannonball bounced off the Titan and came straight back.", lvl: 2 },
  { w: "sp[y]glass", p: "compound", parts: ["spy", "glass"], s: "Through the spyglass, the island looks like a sleeping whale.", lvl: 2 },
  { w: "hid[e]out", p: "compound", parts: ["hide", "out"], s: "The monkey's hideout is a hollow log with a tiny door.", lvl: 2 },
  { w: "jell[y]fish", p: "compound", parts: ["jelly", "fish"], s: "A jellyfish fiend glows pink whenever it feels embarrassed.", lvl: 2 },
  { w: "pin[ea]pple", p: "compound", parts: ["pine", "apple"], s: "Honest Hal sells a pineapple as a 'tropical helmet.'", lvl: 2 },
  { w: "dri[ft]wood", p: "compound", parts: ["drift", "wood"], s: "The pirates built a whole town out of driftwood and stubbornness.", lvl: 2 },
  { w: "l[igh]thouse", p: "compound", parts: ["light", "house"], s: "The lighthouse keeper is a ghost who is afraid of the dark.", lvl: 2 },
  { w: "[ear]thquake", p: "compound", parts: ["earth", "quake"], s: "Every time the Titan sneezes, the island has an earthquake.", lvl: 3 },
  { w: "glo[ww]orm", p: "compound", parts: ["glow", "worm"], s: "One glowworm lit the whole cave and took all the credit.", lvl: 3 },
  { w: "fis[hh]ook", p: "compound", parts: ["fish", "hook"], s: "The pirate's fishhook caught a boot, a hat, and an angry eel.", lvl: 3 },
  { w: "nigh[tt]ime", p: "compound", parts: ["night", "time"], s: "At nighttime, the jungle glows and the frogs sing off-key.", lvl: 3 },

  // digraph_review: ph, ch (as /k/), tch, dge.
  { w: "dol[ph]in", p: "digraph_review", s: "A dolphin guided our ship past the reef, then asked for a fish.", lvl: 1 },
  { w: "s[ch]ool", p: "digraph_review", s: "Even pirates go to school, where they mostly study maps and yelling.", lvl: 1 },
  { w: "ca[tch]", p: "digraph_review", s: "Catch the falling crystal before it bonks the droid.", lvl: 1 },
  { w: "ha[tch]", p: "digraph_review", s: "Titan eggs hatch faster if you read them a really good story.", lvl: 1 },
  { w: "swi[tch]", p: "digraph_review", s: "Never flip the droid's off switch, because it holds grudges.", lvl: 1 },
  { w: "bri[dge]", p: "digraph_review", s: "The rope bridge wobbles, sways, and tells you it's fine.", lvl: 1 },
  { w: "ba[dge]", p: "digraph_review", s: "The droid made itself a captain's badge out of a spoon.", lvl: 1 },
  { w: "[ph]antom", p: "digraph_review", s: "The phantom ship glows green and plays very sad accordion music.", lvl: 2 },
  { w: "tro[ph]y", p: "digraph_review", s: "The droid gave itself a trophy for 'Best Droid.'", lvl: 2 },
  { w: "al[ph]abet", p: "digraph_review", s: "Captain Jumble hid half the alphabet inside a sock.", lvl: 2 },
  { w: "gra[ph]", p: "digraph_review", s: "The storm graph shows rain, more rain, and surprise rain.", lvl: 2 },
  { w: "e[ch]o", p: "digraph_review", s: "In the empty temple, your echo always gets the last word.", lvl: 2 },
  { w: "an[ch]or", p: "digraph_review", s: "Drop the anchor, unless the parrot is still sitting on it.", lvl: 2 },
  { w: "scra[tch]", p: "digraph_review", s: "The beetle fiend left a scratch on the Knight's brand-new armor.", lvl: 2 },
  { w: "ga[dge]t", p: "digraph_review", s: "The droid has a gadget for everything except opening doors.", lvl: 2 },
  { w: "s[ch]eme", p: "digraph_review", s: "Captain Jumble's latest scheme involves a giant magnet and lots of yelling.", lvl: 3 },
  { w: "knowle[dge]", p: "digraph_review", s: "Lore Crystals hold all the knowledge of the Sundered Isles.", lvl: 3 },

  // silent_review: the pair with the silent letter (kn, wr, mb, gn).
  { w: "[kn]ight", p: "silent_review", s: "A knight in heavy armor should never try to swim.", lvl: 1 },
  { w: "[kn]ot", p: "silent_review", s: "The sailor tied a knot so tight that nobody can ever untie it.", lvl: 1 },
  { w: "[kn]ock", p: "silent_review", s: "Knock twice on the temple door, then run.", lvl: 1 },
  { w: "[wr]ist", p: "silent_review", s: "The droid wears a tiny compass on its wrist.", lvl: 1 },
  { w: "[wr]ong", p: "silent_review", s: "Every wrong answer gives the fiend a chance to dodge.", lvl: 1 },
  { w: "[wr]ite", p: "silent_review", s: "Write a mighty entrance, and your Titan will burst onto the screen.", lvl: 1 },
  { w: "thu[mb]", p: "silent_review", s: "The Titan picked up our ship between its thumb and finger.", lvl: 1 },
  { w: "cli[mb]", p: "silent_review", s: "Climb the pillar to reach the crystal, but watch out for bats.", lvl: 1 },
  { w: "co[mb]", p: "silent_review", s: "The droid owns a comb but has no hair.", lvl: 1 },
  { w: "si[gn]", p: "silent_review", s: "The sign says 'Beware of Monkey,' and the monkey wrote it.", lvl: 1 },
  { w: "[gn]ome", p: "silent_review", s: "The garden gnome on the dock is actually a spy.", lvl: 2 },
  { w: "[wr]ench", p: "silent_review", s: "The droid fixes everything with a wrench and a long sigh.", lvl: 2 },
  { w: "to[mb]", p: "silent_review", s: "The ancient tomb has a sign on the door that says 'Please knock.'", lvl: 2 },
  { w: "[gn]at", p: "silent_review", s: "A gnat flew into the Titan's ear, and the Titan lost the battle.", lvl: 2 },
  { w: "[kn]uckle", p: "silent_review", s: "The Titan cracked one knuckle, and the whole valley echoed.", lvl: 3 },
  { w: "[wr]estle", p: "silent_review", s: "Never wrestle an octopus, because it has more arms than you.", lvl: 3 },
  { w: "desi[gn]", p: "silent_review", s: "Design a flood wall that can stop a giant wave.", lvl: 3 },

  // diphthong_review: the vowel pair (oi, oy, ou, ow, au, aw, oo).
  { w: "c[oi]n", p: "diphthong_review", s: "Flip a coin: heads we fight, tails the droid fights.", lvl: 1 },
  { w: "cl[ou]d", p: "diphthong_review", s: "The airship hid inside a cloud shaped like a duck.", lvl: 1 },
  { w: "t[ow]er", p: "diphthong_review", s: "The wizard's tower leans so much that the stairs go sideways.", lvl: 1 },
  { w: "gr[ow]l", p: "diphthong_review", s: "The fiend's belly let out a growl louder than the fiend.", lvl: 1 },
  { w: "cl[aw]", p: "diphthong_review", s: "One crab claw can open a treasure chest or a coconut.", lvl: 1 },
  { w: "bamb[oo]", p: "diphthong_review", s: "The jungle village is made of bamboo, vines, and good luck.", lvl: 1 },
  { w: "sp[oo]ky", p: "diphthong_review", s: "The spooky cave is mostly bats and one very lonely ghost.", lvl: 1 },
  { w: "r[oy]al", p: "diphthong_review", s: "The tiny queen wears her royal crown as a belt.", lvl: 2 },
  { w: "l[au]nch", p: "diphthong_review", s: "Launch the airship before the fiends finish their breakfast.", lvl: 2 },
  { w: "av[oi]d", p: "diphthong_review", s: "Avoid the purple slime, because it hugs.", lvl: 2 },
  { w: "[oy]ster", p: "diphthong_review", s: "The oyster kept its pearl and offered us a pebble instead.", lvl: 2 },
  { w: "m[ou]ntain", p: "diphthong_review", s: "Climbing the mountain took all day, and the goat beat us.", lvl: 2 },
  { w: "v[au]lt", p: "diphthong_review", s: "The treasure vault opens with a magnetic latch and a polite knock.", lvl: 2 },
  { w: "v[oy]age", p: "diphthong_review", s: "Our voyage to the ice island took three days and forty snacks.", lvl: 3 },
  { w: "th[ou]sand", p: "diphthong_review", s: "The Leviathan is a thousand feet long and scared of jellyfish.", lvl: 3 },
  { w: "dinos[au]r", p: "diphthong_review", s: "This Titan looks like a dinosaur wearing a crystal crown.", lvl: 3 },
  { w: "squ[aw]k", p: "diphthong_review", s: "The parrot let out a squawk so loud that the fiends ducked.", lvl: 3 },
];

const BRACKETED = /^([^\[\]]*)\[([^\[\]]+)\]([^\[\]]*)$/;

/**
 * Splits a bank word at its bracketed tricky part.
 * parseWord("fr[ie]nd") → { word: "friend", before: "fr", focus: "ie", after: "nd" }
 * Throws if `w` doesn't have exactly one non-empty [bracketed] span.
 */
export function parseWord(w) {
  const m = BRACKETED.exec(w);
  if (!m) throw new Error(`parseWord: "${w}" needs exactly one [bracketed] part`);
  const [, before, focus, after] = m;
  return { word: before + focus + after, before, focus, after };
}
